name: ' '
favicon: null
layout_spectrum: 0.76117
typography_spectrum: 0.70422
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#edebdc'
    - '#baaf39'
    - '#795a48'
    - '#8f942c'
    - '#252e4d'
  brandStrength: 0
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
