name: Lonestar Rustic Supply
favicon: null
layout_spectrum: 0
typography_spectrum: 0.24292
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fec073'
    - '#8e6140'
    - '#5f2414'
    - '#a3e1d4'
    - '#147e74'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
