name: Lonestar Rustic Supply
favicon: null
layout_spectrum: 0.2438
typography_spectrum: 0.51324
title: Lonestar Rustic Supply
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fec073'
    - '#8e6140'
    - '#5f2414'
    - '#a3e1d4'
    - '#147e74'
  brandStrength: 0
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
