name: Lonestar Rustic Supply
favicon: null
layout_spectrum: 1
typography_spectrum: 0.09654
title: Lonestar Rustic Supply
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#12060a'
    - '#c1badc'
    - '#892024'
    - '#985633'
  brandStrength: 0.6875
  lightness: 0.1875
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
