name: Lonestar Rustic Supply
favicon: null
layout_spectrum: 1
typography_spectrum: 0.11889
title: Lonestar Rustic Supply
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fec073'
    - '#8e6140'
    - '#5f2414'
    - '#a3e1d4'
    - '#147e74'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
